export enum ErrorCode {
  // Auth
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',

  // Projects
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_KEY_EXISTS = 'PROJECT_KEY_EXISTS',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',

  // Issues
  ISSUE_NOT_FOUND = 'ISSUE_NOT_FOUND',
  ISSUE_INVALID_TRANSITION = 'ISSUE_INVALID_TRANSITION',

  // Sprints
  SPRINT_NOT_FOUND = 'SPRINT_NOT_FOUND',
  SPRINT_ALREADY_ACTIVE = 'SPRINT_ALREADY_ACTIVE',

  // Comments
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',

  // File Upload
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // General
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
