export enum ErrorCode {
  // Auth
  AUTH_EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',

  // Users
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_EXISTS = 'USER_EMAIL_EXISTS',

  // Projects
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_KEY_EXISTS = 'PROJECT_KEY_EXISTS',
  PROJECT_ACCESS_DENIED = 'PROJECT_ACCESS_DENIED',
  PROJECT_MEMBER_EXISTS = 'PROJECT_MEMBER_EXISTS',
  PROJECT_MEMBER_NOT_FOUND = 'PROJECT_MEMBER_NOT_FOUND',
  PROJECT_LAST_OWNER = 'PROJECT_LAST_OWNER',
  PROJECT_LABEL_EXISTS = 'PROJECT_LABEL_EXISTS',
  PROJECT_LABEL_NOT_FOUND = 'PROJECT_LABEL_NOT_FOUND',

  // Issues
  ISSUE_NOT_FOUND = 'ISSUE_NOT_FOUND',
  ISSUE_INVALID_TRANSITION = 'ISSUE_INVALID_TRANSITION',
  ISSUE_KEY_NOT_FOUND = 'ISSUE_KEY_NOT_FOUND',
  ISSUE_ASSIGNEE_NOT_PROJECT_MEMBER = 'ISSUE_ASSIGNEE_NOT_PROJECT_MEMBER',
  ISSUE_LABEL_NOT_FOUND = 'ISSUE_LABEL_NOT_FOUND',

  // Attachments
  ATTACHMENT_NOT_FOUND = 'ATTACHMENT_NOT_FOUND',
  ATTACHMENT_DELETE_FORBIDDEN = 'ATTACHMENT_DELETE_FORBIDDEN',

  // Sprints
  SPRINT_NOT_FOUND = 'SPRINT_NOT_FOUND',
  SPRINT_ALREADY_ACTIVE = 'SPRINT_ALREADY_ACTIVE',
  SPRINT_INVALID_TRANSITION = 'SPRINT_INVALID_TRANSITION',
  SPRINT_MISSING_DATES = 'SPRINT_MISSING_DATES',

  // Comments
  COMMENT_NOT_FOUND = 'COMMENT_NOT_FOUND',
  COMMENT_FORBIDDEN = 'COMMENT_FORBIDDEN',
  COMMENT_INVALID_PARENT = 'COMMENT_INVALID_PARENT',

  // Admin
  ADMIN_ACCESS_DENIED = 'ADMIN_ACCESS_DENIED',
  ADMIN_CANNOT_DELETE_SELF = 'ADMIN_CANNOT_DELETE_SELF',
  ADMIN_CANNOT_DEMOTE_SELF = 'ADMIN_CANNOT_DEMOTE_SELF',

  // Notifications
  NOTIFICATION_NOT_FOUND = 'NOTIFICATION_NOT_FOUND',

  // WebSocket
  WS_RATE_LIMIT_EXCEEDED = 'WS_RATE_LIMIT_EXCEEDED',
  WS_UNAUTHORIZED_ROOM = 'WS_UNAUTHORIZED_ROOM',

  // File Upload
  FILE_TYPE_NOT_ALLOWED = 'FILE_TYPE_NOT_ALLOWED',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // General
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
}
